apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-qvsgrxsv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/python-qvsgrxsv:908ae8b9a4d541a6bbc342ea620187e148988729@sha256:4ea146581a39cda5d5c121a74d8ef946b9c41d630e22f6baf659b76686786c05
        name: container-image  
